LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := libzzip
LOCAL_MODULE_FILENAME := libzzip
LOCAL_SRC_FILES := libs/$(TARGET_ARCH_ABI)/libzzip.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
include $(PREBUILT_STATIC_LIBRARY)
